version: "3.9"

services:
  excite-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: excite_api
    ports:
      - "5001:5001"   # host:container
    env_file: "local.env"
    environment:
      AWS_PROFILE: default
    volumes:
      - ${HOME}/.aws:/root/.aws:ro
    command: ["python", "main.py"]
    restart: unless-stopped
    networks:
      - dbaccess
  
networks:
  dbaccess:
    external: true